window.WORLD_CUP_DATA = {
  updatedAt: "2026-06-02",
  source: "FIFA match schedule / Wikipedia 2026 FIFA World Cup pages checked 2026-06-02",
  note: "조별리그 실제 조편성 기준입니다. 32강 이후는 공식 토너먼트 슬롯이며, 조별 순위 확정 후 국가명으로 교체됩니다.",
  teams: {
    MEX: {"nameKo": "멕시코", "nameEn": "Mexico", "flag": "🇲🇽", "confed": "CONCACAF", "status": "A1 · 개최국", "squadUrl": "https://en.wikipedia.org/wiki/Mexico_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    RSA: {"nameKo": "남아공", "nameEn": "South Africa", "flag": "🇿🇦", "confed": "CAF", "status": "A2", "squadUrl": "https://en.wikipedia.org/wiki/South_Africa_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    KOR: {"nameKo": "대한민국", "nameEn": "South Korea", "flag": "🇰🇷", "confed": "AFC", "status": "A3", "squadUrl": "https://en.wikipedia.org/wiki/South_Korea_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CZE: {"nameKo": "체코", "nameEn": "Czechia", "flag": "🇨🇿", "confed": "UEFA", "status": "A4", "squadUrl": "https://en.wikipedia.org/wiki/Czechia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CAN: {"nameKo": "캐나다", "nameEn": "Canada", "flag": "🇨🇦", "confed": "CONCACAF", "status": "B1 · 개최국", "squadUrl": "https://en.wikipedia.org/wiki/Canada_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    BIH: {"nameKo": "보스니아 헤르체고비나", "nameEn": "Bosnia and Herzegovina", "flag": "🇧🇦", "confed": "UEFA", "status": "B2", "squadUrl": "https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    QAT: {"nameKo": "카타르", "nameEn": "Qatar", "flag": "🇶🇦", "confed": "AFC", "status": "B3", "squadUrl": "https://en.wikipedia.org/wiki/Qatar_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    SUI: {"nameKo": "스위스", "nameEn": "Switzerland", "flag": "🇨🇭", "confed": "UEFA", "status": "B4", "squadUrl": "https://en.wikipedia.org/wiki/Switzerland_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    BRA: {"nameKo": "브라질", "nameEn": "Brazil", "flag": "🇧🇷", "confed": "CONMEBOL", "status": "C1", "squadUrl": "https://en.wikipedia.org/wiki/Brazil_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    MAR: {"nameKo": "모로코", "nameEn": "Morocco", "flag": "🇲🇦", "confed": "CAF", "status": "C2", "squadUrl": "https://en.wikipedia.org/wiki/Morocco_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    HAI: {"nameKo": "아이티", "nameEn": "Haiti", "flag": "🇭🇹", "confed": "CONCACAF", "status": "C3", "squadUrl": "https://en.wikipedia.org/wiki/Haiti_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    SCO: {"nameKo": "스코틀랜드", "nameEn": "Scotland", "flag": "🏴", "confed": "UEFA", "status": "C4", "squadUrl": "https://en.wikipedia.org/wiki/Scotland_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    USA: {"nameKo": "미국", "nameEn": "United States", "flag": "🇺🇸", "confed": "CONCACAF", "status": "D1 · 개최국", "squadUrl": "https://en.wikipedia.org/wiki/United_States_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    PAR: {"nameKo": "파라과이", "nameEn": "Paraguay", "flag": "🇵🇾", "confed": "CONMEBOL", "status": "D2", "squadUrl": "https://en.wikipedia.org/wiki/Paraguay_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    AUS: {"nameKo": "호주", "nameEn": "Australia", "flag": "🇦🇺", "confed": "AFC", "status": "D3", "squadUrl": "https://en.wikipedia.org/wiki/Australia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    TUR: {"nameKo": "튀르키예", "nameEn": "Turkey", "flag": "🇹🇷", "confed": "UEFA", "status": "D4", "squadUrl": "https://en.wikipedia.org/wiki/Turkey_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    GER: {"nameKo": "독일", "nameEn": "Germany", "flag": "🇩🇪", "confed": "UEFA", "status": "E1", "squadUrl": "https://en.wikipedia.org/wiki/Germany_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CUW: {"nameKo": "퀴라소", "nameEn": "Curaçao", "flag": "🇨🇼", "confed": "CONCACAF", "status": "E2", "squadUrl": "https://en.wikipedia.org/wiki/Curaçao_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CIV: {"nameKo": "코트디부아르", "nameEn": "Ivory Coast", "flag": "🇨🇮", "confed": "CAF", "status": "E3", "squadUrl": "https://en.wikipedia.org/wiki/Ivory_Coast_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    ECU: {"nameKo": "에콰도르", "nameEn": "Ecuador", "flag": "🇪🇨", "confed": "CONMEBOL", "status": "E4", "squadUrl": "https://en.wikipedia.org/wiki/Ecuador_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    NED: {"nameKo": "네덜란드", "nameEn": "Netherlands", "flag": "🇳🇱", "confed": "UEFA", "status": "F1", "squadUrl": "https://en.wikipedia.org/wiki/Netherlands_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    JPN: {"nameKo": "일본", "nameEn": "Japan", "flag": "🇯🇵", "confed": "AFC", "status": "F2", "squadUrl": "https://en.wikipedia.org/wiki/Japan_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    SWE: {"nameKo": "스웨덴", "nameEn": "Sweden", "flag": "🇸🇪", "confed": "UEFA", "status": "F3", "squadUrl": "https://en.wikipedia.org/wiki/Sweden_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    TUN: {"nameKo": "튀니지", "nameEn": "Tunisia", "flag": "🇹🇳", "confed": "CAF", "status": "F4", "squadUrl": "https://en.wikipedia.org/wiki/Tunisia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    BEL: {"nameKo": "벨기에", "nameEn": "Belgium", "flag": "🇧🇪", "confed": "UEFA", "status": "G1", "squadUrl": "https://en.wikipedia.org/wiki/Belgium_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    EGY: {"nameKo": "이집트", "nameEn": "Egypt", "flag": "🇪🇬", "confed": "CAF", "status": "G2", "squadUrl": "https://en.wikipedia.org/wiki/Egypt_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    IRN: {"nameKo": "이란", "nameEn": "Iran", "flag": "🇮🇷", "confed": "AFC", "status": "G3", "squadUrl": "https://en.wikipedia.org/wiki/Iran_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    NZL: {"nameKo": "뉴질랜드", "nameEn": "New Zealand", "flag": "🇳🇿", "confed": "OFC", "status": "G4", "squadUrl": "https://en.wikipedia.org/wiki/New_Zealand_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    ESP: {"nameKo": "스페인", "nameEn": "Spain", "flag": "🇪🇸", "confed": "UEFA", "status": "H1", "squadUrl": "https://en.wikipedia.org/wiki/Spain_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CPV: {"nameKo": "카보베르데", "nameEn": "Cape Verde", "flag": "🇨🇻", "confed": "CAF", "status": "H2", "squadUrl": "https://en.wikipedia.org/wiki/Cape_Verde_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    KSA: {"nameKo": "사우디아라비아", "nameEn": "Saudi Arabia", "flag": "🇸🇦", "confed": "AFC", "status": "H3", "squadUrl": "https://en.wikipedia.org/wiki/Saudi_Arabia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    URU: {"nameKo": "우루과이", "nameEn": "Uruguay", "flag": "🇺🇾", "confed": "CONMEBOL", "status": "H4", "squadUrl": "https://en.wikipedia.org/wiki/Uruguay_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    FRA: {"nameKo": "프랑스", "nameEn": "France", "flag": "🇫🇷", "confed": "UEFA", "status": "I1", "squadUrl": "https://en.wikipedia.org/wiki/France_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    SEN: {"nameKo": "세네갈", "nameEn": "Senegal", "flag": "🇸🇳", "confed": "CAF", "status": "I2", "squadUrl": "https://en.wikipedia.org/wiki/Senegal_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    IRQ: {"nameKo": "이라크", "nameEn": "Iraq", "flag": "🇮🇶", "confed": "AFC", "status": "I3", "squadUrl": "https://en.wikipedia.org/wiki/Iraq_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    NOR: {"nameKo": "노르웨이", "nameEn": "Norway", "flag": "🇳🇴", "confed": "UEFA", "status": "I4", "squadUrl": "https://en.wikipedia.org/wiki/Norway_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    ARG: {"nameKo": "아르헨티나", "nameEn": "Argentina", "flag": "🇦🇷", "confed": "CONMEBOL", "status": "J1 · 디펜딩 챔피언", "squadUrl": "https://en.wikipedia.org/wiki/Argentina_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    ALG: {"nameKo": "알제리", "nameEn": "Algeria", "flag": "🇩🇿", "confed": "CAF", "status": "J2", "squadUrl": "https://en.wikipedia.org/wiki/Algeria_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    AUT: {"nameKo": "오스트리아", "nameEn": "Austria", "flag": "🇦🇹", "confed": "UEFA", "status": "J3", "squadUrl": "https://en.wikipedia.org/wiki/Austria_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    JOR: {"nameKo": "요르단", "nameEn": "Jordan", "flag": "🇯🇴", "confed": "AFC", "status": "J4", "squadUrl": "https://en.wikipedia.org/wiki/Jordan_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    POR: {"nameKo": "포르투갈", "nameEn": "Portugal", "flag": "🇵🇹", "confed": "UEFA", "status": "K1", "squadUrl": "https://en.wikipedia.org/wiki/Portugal_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    COD: {"nameKo": "DR 콩고", "nameEn": "DR Congo", "flag": "🇨🇩", "confed": "CAF", "status": "K2", "squadUrl": "https://en.wikipedia.org/wiki/DR_Congo_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    UZB: {"nameKo": "우즈베키스탄", "nameEn": "Uzbekistan", "flag": "🇺🇿", "confed": "AFC", "status": "K3", "squadUrl": "https://en.wikipedia.org/wiki/Uzbekistan_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    COL: {"nameKo": "콜롬비아", "nameEn": "Colombia", "flag": "🇨🇴", "confed": "CONMEBOL", "status": "K4", "squadUrl": "https://en.wikipedia.org/wiki/Colombia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    ENG: {"nameKo": "잉글랜드", "nameEn": "England", "flag": "🏴", "confed": "UEFA", "status": "L1", "squadUrl": "https://en.wikipedia.org/wiki/England_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    CRO: {"nameKo": "크로아티아", "nameEn": "Croatia", "flag": "🇭🇷", "confed": "UEFA", "status": "L2", "squadUrl": "https://en.wikipedia.org/wiki/Croatia_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    GHA: {"nameKo": "가나", "nameEn": "Ghana", "flag": "🇬🇭", "confed": "CAF", "status": "L3", "squadUrl": "https://en.wikipedia.org/wiki/Ghana_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]},
    PAN: {"nameKo": "파나마", "nameEn": "Panama", "flag": "🇵🇦", "confed": "CONCACAF", "status": "L4", "squadUrl": "https://en.wikipedia.org/wiki/Panama_national_football_team", "squad": ["최종 선수명단 발표 후 업데이트"]}
  },
  groups: {
    A: ["MEX", "RSA", "KOR", "CZE"],
    B: ["CAN", "BIH", "QAT", "SUI"],
    C: ["BRA", "MAR", "HAI", "SCO"],
    D: ["USA", "PAR", "AUS", "TUR"],
    E: ["GER", "CUW", "CIV", "ECU"],
    F: ["NED", "JPN", "SWE", "TUN"],
    G: ["BEL", "EGY", "IRN", "NZL"],
    H: ["ESP", "CPV", "KSA", "URU"],
    I: ["FRA", "SEN", "IRQ", "NOR"],
    J: ["ARG", "ALG", "AUT", "JOR"],
    K: ["POR", "COD", "UZB", "COL"],
    L: ["ENG", "CRO", "GHA", "PAN"]
  },
  rounds: [
    { id: "r32", title: "32강", matches: [
      {"id": "M73", "label": "Match 73", "teams": ["Winner Group E", "3rd Group A/B/C/D/F"], "winner": "", "time": "June 29 · Foxborough"},
      {"id": "M74", "label": "Match 74", "teams": ["Winner Group I", "3rd Group C/D/F/G/H"], "winner": "", "time": "June 30 · East Rutherford"},
      {"id": "M75", "label": "Match 75", "teams": ["Runner-up Group A", "Runner-up Group B"], "winner": "", "time": "June 28 · Inglewood"},
      {"id": "M76", "label": "Match 76", "teams": ["Winner Group F", "Runner-up Group C"], "winner": "", "time": "June 29 · Guadalupe"},
      {"id": "M77", "label": "Match 77", "teams": ["Runner-up Group K", "Runner-up Group L"], "winner": "", "time": "July 2 · Toronto"},
      {"id": "M78", "label": "Match 78", "teams": ["Winner Group H", "Runner-up Group J"], "winner": "", "time": "July 2 · Inglewood"},
      {"id": "M79", "label": "Match 79", "teams": ["Winner Group D", "3rd Group B/E/F/I/J"], "winner": "", "time": "July 1 · Santa Clara"},
      {"id": "M80", "label": "Match 80", "teams": ["Winner Group G", "3rd Group A/E/H/I/J"], "winner": "", "time": "July 1 · Seattle"},
      {"id": "M81", "label": "Match 81", "teams": ["Winner Group C", "Runner-up Group F"], "winner": "", "time": "June 29 · Houston"},
      {"id": "M82", "label": "Match 82", "teams": ["Runner-up Group E", "Runner-up Group I"], "winner": "", "time": "June 30 · Arlington"},
      {"id": "M83", "label": "Match 83", "teams": ["Winner Group A", "3rd Group C/E/F/H/I"], "winner": "", "time": "June 30 · Mexico City"},
      {"id": "M84", "label": "Match 84", "teams": ["Winner Group L", "3rd Group E/H/I/J/K"], "winner": "", "time": "July 1 · Atlanta"},
      {"id": "M85", "label": "Match 85", "teams": ["Winner Group J", "Runner-up Group H"], "winner": "", "time": "July 3 · Miami Gardens"},
      {"id": "M86", "label": "Match 86", "teams": ["Runner-up Group D", "Runner-up Group G"], "winner": "", "time": "July 3 · Arlington"},
      {"id": "M87", "label": "Match 87", "teams": ["Winner Group B", "3rd Group E/F/G/I/J"], "winner": "", "time": "July 2 · Vancouver"},
      {"id": "M88", "label": "Match 88", "teams": ["Winner Group K", "3rd Group D/E/I/J/L"], "winner": "", "time": "July 3 · Kansas City"}
    ]},
    { id: "r16", title: "16강", matches: [
      {"id": "M89", "label": "Match 89", "teams": ["Winner Match 74", "Winner Match 77"], "winner": "", "time": "July 4 · Philadelphia"},
      {"id": "M90", "label": "Match 90", "teams": ["Winner Match 73", "Winner Match 75"], "winner": "", "time": "July 4 · Houston"},
      {"id": "M91", "label": "Match 91", "teams": ["Winner Match 83", "Winner Match 84"], "winner": "", "time": "July 6 · Arlington"},
      {"id": "M92", "label": "Match 92", "teams": ["Winner Match 81", "Winner Match 82"], "winner": "", "time": "July 6 · Seattle"},
      {"id": "M93", "label": "Match 93", "teams": ["Winner Match 76", "Winner Match 78"], "winner": "", "time": "July 5 · East Rutherford"},
      {"id": "M94", "label": "Match 94", "teams": ["Winner Match 79", "Winner Match 80"], "winner": "", "time": "July 5 · Mexico City"},
      {"id": "M95", "label": "Match 95", "teams": ["Winner Match 86", "Winner Match 88"], "winner": "", "time": "July 7 · Atlanta"},
      {"id": "M96", "label": "Match 96", "teams": ["Winner Match 85", "Winner Match 87"], "winner": "", "time": "July 7 · Vancouver"}
    ]},
    { id: "qf", title: "8강", matches: [
      {"id": "M97", "label": "Match 97", "teams": ["Winner Match 89", "Winner Match 90"], "winner": "", "time": "July 9 · Foxborough"},
      {"id": "M98", "label": "Match 98", "teams": ["Winner Match 93", "Winner Match 94"], "winner": "", "time": "July 10 · Inglewood"},
      {"id": "M99", "label": "Match 99", "teams": ["Winner Match 91", "Winner Match 92"], "winner": "", "time": "July 11 · Miami Gardens"},
      {"id": "M100", "label": "Match 100", "teams": ["Winner Match 95", "Winner Match 96"], "winner": "", "time": "July 11 · Kansas City"}
    ]},
    { id: "sf", title: "4강", matches: [
      {"id": "M101", "label": "Match 101", "teams": ["Winner Match 97", "Winner Match 98"], "winner": "", "time": "July 14 · Arlington"},
      {"id": "M102", "label": "Match 102", "teams": ["Winner Match 99", "Winner Match 100"], "winner": "", "time": "July 15 · Atlanta"}
    ]},
    { id: "final", title: "결승/3위전", matches: [
      {"id": "M103", "label": "결승", "teams": ["Winner Match 101", "Winner Match 102"], "winner": "", "time": "July 19 · East Rutherford"},
      {"id": "M104", "label": "3위전", "teams": ["Loser Match 101", "Loser Match 102"], "winner": "", "time": "July 18 · Miami Gardens"}
    ]},
    { id: "champion", title: "우승", matches: [
      {"id": "M105", "label": "우승", "teams": ["Winner Match 103"], "winner": "", "time": ""}
    ]}
  ]
};
